packages:
  - mf_provider_app
  - mf_lib
  - mf_react_rsbuild
  - mf_react_vite
  - mf_react_webpack
  - mf_angular_webpack
  - mf_vue_vite
  - mf_svelte_vite
  - mfe_cli
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - unrs-resolver
