packages:
  - mf_cart
  - mf_checkout
  - mf_products
  - mf_shared_lib
  - mf_shell
  - mf_user

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - unrs-resolver
